# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 541ffc9ca4d05776adf8159ab730c5ed54c63f41b451b726c87fa98a45186647f09eb09a6f231d14957283749c4fe19261e8e0619365885d1d356bcfabda523c

test:
  secret_key_base: 616a09dff9eb919654f9dbb15f7123dcf354579e0df6c476424a6c6232547c2746baf6ee4e6b6a32b5b4f8fe567e34d3e0221ca6c3bfae8827f167dc2a21164f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
